ALTER TABLE `administrador_sistema` CHANGE `id_usuario` `id_usuario` int(11) COMMENT 'Número que identifica o usuário.';
ALTER TABLE `administrador_sistema` CHANGE `id_sistema` `id_sistema` int(11) COMMENT 'Número que identifica o sistema. 100000099: SIP; 100000100: SEI';
ALTER TABLE `contexto` CHANGE `id_contexto` `id_contexto` int(11) COMMENT 'Número que identifica o contexto.';
ALTER TABLE `contexto` CHANGE `id_orgao` `id_orgao` int(11) COMMENT 'Número que identifica o órgão.';
ALTER TABLE `contexto` CHANGE `nome` `nome` varchar(50) COMMENT 'Nome do contexto para efetuar o login.';
ALTER TABLE `contexto` CHANGE `descricao` `descricao` varchar(200) COMMENT 'Descrição do contexto.';
ALTER TABLE `contexto` CHANGE `base_dn_ldap` `base_dn_ldap` varchar(50) COMMENT 'Identifica em qual base está.';
ALTER TABLE `contexto` CHANGE `sin_ativo` `sin_ativo` char(1) COMMENT 'Variável categórica que identifica se o contexto está ativo ou não. S: Sim N: Não';
ALTER TABLE `coordenador_perfil` CHANGE `id_perfil` `id_perfil` int(11) COMMENT 'Número que identifica o tipo de perfil do coordenador.';
ALTER TABLE `coordenador_perfil` CHANGE `id_usuario` `id_usuario` int(11) COMMENT 'Número que identifica o usuário coordenador.';
ALTER TABLE `coordenador_perfil` CHANGE `id_sistema` `id_sistema` int(11) COMMENT 'Número que identifica o sistema. ';
ALTER TABLE `coordenador_unidade` CHANGE `id_sistema` `id_sistema` int(11) COMMENT 'Número que identifica o sistema.';
ALTER TABLE `coordenador_unidade` CHANGE `id_usuario` `id_usuario` int(11) COMMENT 'Número que identifica o usuário coordenador da unidade.';
ALTER TABLE `coordenador_unidade` CHANGE `id_unidade` `id_unidade` int(11) COMMENT 'Número que identifica a unidade.';
ALTER TABLE `grupo_rede` CHANGE `id_grupo_rede` `id_grupo_rede` int(11) COMMENT 'Número que identifica o grupo de rede.';
ALTER TABLE `grupo_rede` CHANGE `id_orgao` `id_orgao` int(11) COMMENT 'Número que identifica o órgão.';
ALTER TABLE `grupo_rede` CHANGE `ou_ldap` `ou_ldap` varchar(256) COMMENT 'Unidade Organizacional LDAP.';
ALTER TABLE `grupo_rede` CHANGE `sin_excecao` `sin_excecao` char(1) COMMENT 'Variável categórica que identifica se o grupo de rede é exceção.';
ALTER TABLE `grupo_rede` CHANGE `descricao` `descricao` longtext COMMENT 'Descrição do grupo de rede.';
ALTER TABLE `hierarquia` CHANGE `id_hierarquia` `id_hierarquia` int(11) COMMENT 'Número que identifica a hierarquia.';
ALTER TABLE `hierarquia` CHANGE `nome` `nome` varchar(50) COMMENT 'Nome do sistema.';
ALTER TABLE `hierarquia` CHANGE `descricao` `descricao` varchar(200) COMMENT 'Descrição da hierarquia criada.';
ALTER TABLE `hierarquia` CHANGE `dta_inicio` `dta_inicio` datetime COMMENT 'Data de início da hierarquia.';
ALTER TABLE `hierarquia` CHANGE `dta_fim` `dta_fim` datetime COMMENT 'Data de fim da hierarquia.';
ALTER TABLE `hierarquia` CHANGE `sin_ativo` `sin_ativo` char(1) COMMENT 'Variável categórica que identifica se a hierarquia está ativa ou não. S: Sim N: Não';
ALTER TABLE `infra_agendamento_tarefa` CHANGE `id_infra_agendamento_tarefa` `id_infra_agendamento_tarefa` int(11) COMMENT 'Número que identifica a tarefa de agendamento.';
ALTER TABLE `infra_agendamento_tarefa` CHANGE `descricao` `descricao` varchar(500) COMMENT 'Descrição da tarefa de agendamento.';
ALTER TABLE `infra_agendamento_tarefa` CHANGE `comando` `comando` varchar(255) COMMENT 'Comando da tarefa de agendamento.';
ALTER TABLE `infra_agendamento_tarefa` CHANGE `sta_periodicidade_execucao` `sta_periodicidade_execucao` char(1) COMMENT 'Variável categórica que indica a periodicidade de execução da tarefa. D: Diário S: Semanal M: Mensal A: Anual';
ALTER TABLE `infra_agendamento_tarefa` CHANGE `periodicidade_complemento` `periodicidade_complemento` varchar(100) COMMENT 'Hora na qual a tarefa irá iniciar. Apenas números.';
ALTER TABLE `infra_agendamento_tarefa` CHANGE `dth_ultima_execucao` `dth_ultima_execucao` datetime COMMENT 'Data e horário da última execução da tarefa.';
ALTER TABLE `infra_agendamento_tarefa` CHANGE `dth_ultima_conclusao` `dth_ultima_conclusao` datetime COMMENT 'Data e horário da conclusão da última execução da tarefa.';
ALTER TABLE `infra_agendamento_tarefa` CHANGE `sin_sucesso` `sin_sucesso` char(1) COMMENT 'Variável categórica que identifica se a tarefa foi concluída com sucesso ou não. S: Sim N: Não';
ALTER TABLE `infra_agendamento_tarefa` CHANGE `parametro` `parametro` varchar(250) COMMENT 'Indica se existem condicionalidades para a tarefa.';
ALTER TABLE `infra_agendamento_tarefa` CHANGE `email_erro` `email_erro` varchar(250) COMMENT 'Endereço de e-mail do servidor responsável em verificar se a tarefa foi concluída com sucesso.';
ALTER TABLE `infra_agendamento_tarefa` CHANGE `sin_ativo` `sin_ativo` char(1) COMMENT 'Variável categórica que indica se a tarefa está ativa ou não. S: Sim N: Não';
ALTER TABLE `infra_auditoria` CHANGE `id_infra_auditoria` `id_infra_auditoria` bigint(20) COMMENT 'Número que identifica a auditoria.';
ALTER TABLE `infra_auditoria` CHANGE `recurso` `recurso` varchar(50) COMMENT 'Nome do recurso (nome da função no código).';
ALTER TABLE `infra_auditoria` CHANGE `dth_acesso` `dth_acesso` datetime COMMENT 'Data de acesso.';
ALTER TABLE `infra_auditoria` CHANGE `ip` `ip` varchar(39) COMMENT 'IP.';
ALTER TABLE `infra_auditoria` CHANGE `id_usuario` `id_usuario` int(11) COMMENT 'Número que identifica o usuário.';
ALTER TABLE `infra_auditoria` CHANGE `sigla_usuario` `sigla_usuario` varchar(100) COMMENT 'Sistema/Login de rede.';
ALTER TABLE `infra_auditoria` CHANGE `nome_usuario` `nome_usuario` varchar(100) COMMENT 'Nome do usuário.';
ALTER TABLE `infra_auditoria` CHANGE `id_orgao_usuario` `id_orgao_usuario` int(11) COMMENT 'Número que identifica o órgão do usuário.';
ALTER TABLE `infra_auditoria` CHANGE `sigla_orgao_usuario` `sigla_orgao_usuario` varchar(30) COMMENT 'Sigla do órgão do usuário.';
ALTER TABLE `infra_auditoria` CHANGE `id_usuario_emulador` `id_usuario_emulador` int(11) COMMENT 'Número que identifica o usuário emulador.';
ALTER TABLE `infra_auditoria` CHANGE `sigla_usuario_emulador` `sigla_usuario_emulador` varchar(100) COMMENT 'Sistema/Login de rede.';
ALTER TABLE `infra_auditoria` CHANGE `nome_usuario_emulador` `nome_usuario_emulador` varchar(100) COMMENT 'Nome do usuário emulador.';
ALTER TABLE `infra_auditoria` CHANGE `id_orgao_usuario_emulador` `id_orgao_usuario_emulador` int(11) COMMENT 'Número que identifica o órgão do usuário emulador.';
ALTER TABLE `infra_auditoria` CHANGE `sigla_orgao_usuario_emulador` `sigla_orgao_usuario_emulador` varchar(30) COMMENT 'Sigla do órgão do usuário emulador.';
ALTER TABLE `infra_auditoria` CHANGE `id_unidade` `id_unidade` int(11) COMMENT 'Número que identifica a unidade.';
ALTER TABLE `infra_auditoria` CHANGE `sigla_unidade` `sigla_unidade` varchar(30) COMMENT 'Sigla da unidade.';
ALTER TABLE `infra_auditoria` CHANGE `descricao_unidade` `descricao_unidade` varchar(250) COMMENT 'Descrição da unidade.';
ALTER TABLE `infra_auditoria` CHANGE `id_orgao_unidade` `id_orgao_unidade` int(11) COMMENT 'Número que identifica o órgão.';
ALTER TABLE `infra_auditoria` CHANGE `sigla_orgao_unidade` `sigla_orgao_unidade` varchar(30) COMMENT 'Sigla do órgão.';
ALTER TABLE `infra_auditoria` CHANGE `servidor` `servidor` varchar(250) COMMENT 'Nome do servidor.';
ALTER TABLE `infra_auditoria` CHANGE `user_agent` `user_agent` longtext COMMENT 'Tipo de user agent.';
ALTER TABLE `infra_auditoria` CHANGE `requisicao` `requisicao` longtext COMMENT 'Requisição (código).';
ALTER TABLE `infra_auditoria` CHANGE `operacao` `operacao` longtext COMMENT 'Operação (código).';
ALTER TABLE `infra_log` CHANGE `id_infra_log` `id_infra_log` bigint(20) COMMENT 'Número que identifica o log.';
ALTER TABLE `infra_log` CHANGE `dth_log` `dth_log` datetime COMMENT 'Data e hora do log.';
ALTER TABLE `infra_log` CHANGE `texto_log` `texto_log` longtext COMMENT 'Texto do log.';
ALTER TABLE `infra_log` CHANGE `ip` `ip` varchar(39) COMMENT 'IP.';
ALTER TABLE `infra_parametro` CHANGE `nome` `nome` varchar(50) COMMENT 'Nome do parâmetro.';
ALTER TABLE `infra_parametro` CHANGE `valor` `valor` varchar(1024) COMMENT 'Código ou e-mail ';
ALTER TABLE `infra_regra_auditoria` CHANGE `id_infra_regra_auditoria` `id_infra_regra_auditoria` int(11) COMMENT 'Número que identifica a regra de auditoria.';
ALTER TABLE `infra_regra_auditoria` CHANGE `descricao` `descricao` varchar(250) COMMENT 'Descrição da regra de auditoria.';
ALTER TABLE `infra_regra_auditoria` CHANGE `sin_ativo` `sin_ativo` char(1) COMMENT 'Variável categórica que indica se a regra de auditoria está ativa ou não. S: Sim N: Não';
ALTER TABLE `infra_regra_auditoria_recurso` CHANGE `id_infra_regra_auditoria` `id_infra_regra_auditoria` int(11) COMMENT 'Número que identifica a regra de auditoria do recurso.';
ALTER TABLE `infra_regra_auditoria_recurso` CHANGE `recurso` `recurso` varchar(50) COMMENT 'Nome do recurso (nome da função no código).';
ALTER TABLE `infra_sequencia` CHANGE `nome_tabela` `nome_tabela` varchar(30) COMMENT 'Nome da tabela.';
ALTER TABLE `infra_sequencia` CHANGE `qtd_incremento` `qtd_incremento` int(11) COMMENT 'Quantidade que será incrementada ao contador.';
ALTER TABLE `infra_sequencia` CHANGE `num_atual` `num_atual` int(11) COMMENT 'Número atual do contador.';
ALTER TABLE `infra_sequencia` CHANGE `num_maximo` `num_maximo` int(11) COMMENT 'Limite do contador.';
ALTER TABLE `item_menu` CHANGE `id_menu` `id_menu` int(11) COMMENT 'Número que identifica o menu.';
ALTER TABLE `item_menu` CHANGE `id_item_menu` `id_item_menu` int(11) COMMENT 'Número que identifica o item do menu.';
ALTER TABLE `item_menu` CHANGE `id_sistema` `id_sistema` int(11) COMMENT 'Número que identifica o sistema.';
ALTER TABLE `item_menu` CHANGE `id_menu_pai` `id_menu_pai` int(11) COMMENT 'Número que identifica o menu superior.';
ALTER TABLE `item_menu` CHANGE `id_item_menu_pai` `id_item_menu_pai` int(11) COMMENT 'Número que identifica o item do menu superior.';
ALTER TABLE `item_menu` CHANGE `id_recurso` `id_recurso` int(11) COMMENT 'Número que identifica o recurso.';
ALTER TABLE `item_menu` CHANGE `rotulo` `rotulo` varchar(50) COMMENT 'Nome do item do menu.';
ALTER TABLE `item_menu` CHANGE `descricao` `descricao` varchar(200) COMMENT 'Descrição do item do menu.';
ALTER TABLE `item_menu` CHANGE `sequencia` `sequencia` int(11) COMMENT 'Referente ao posicionamento do item no menu vertical.';
ALTER TABLE `item_menu` CHANGE `sin_ativo` `sin_ativo` char(1) COMMENT 'Variável categórica que indica se o item do menu está ativo ou não. S: Sim N: Não';
ALTER TABLE `item_menu` CHANGE `sin_nova_janela` `sin_nova_janela` char(1) COMMENT 'Variável categórica que indica se, ao clicar no item, uma nova janela será aberta. S: Sim N: Não';
ALTER TABLE `login` CHANGE `id_login` `id_login` char(128) COMMENT 'Identificador de login.';
ALTER TABLE `login` CHANGE `id_contexto` `id_contexto` int(11) COMMENT 'Número que identifica o contexto.';
ALTER TABLE `login` CHANGE `id_sistema` `id_sistema` int(11) COMMENT 'Número que identifica o sistema.';
ALTER TABLE `login` CHANGE `id_usuario` `id_usuario` int(11) COMMENT 'Número que identifica o usuário.';
ALTER TABLE `login` CHANGE `dth_login` `dth_login` datetime COMMENT 'Data de login.';
ALTER TABLE `login` CHANGE `id_grupo_rede` `id_grupo_rede` int(11) COMMENT 'Número que identifica o grupo de rede.';
ALTER TABLE `login` CHANGE `hash_interno` `hash_interno` char(128) COMMENT 'Identificador do hash interno.';
ALTER TABLE `login` CHANGE `hash_usuario` `hash_usuario` char(128) COMMENT 'Identificador do hash do usuário.';
ALTER TABLE `login` CHANGE `hash_agente` `hash_agente` char(128) COMMENT 'Identificador do hash do agente.';
ALTER TABLE `login` CHANGE `sin_validado` `sin_validado` char(1) COMMENT 'Variável categórica que identifica se o login foi validado ou não. S: Sim N: Não';
ALTER TABLE `login` CHANGE `id_usuario_emulador` `id_usuario_emulador` int(11) COMMENT 'Número que identifica o usuário.';
ALTER TABLE `login` CHANGE `dn_usuario` `dn_usuario` varchar(255) COMMENT 'Parâmetros do login.';
ALTER TABLE `mapeamento_unidade` CHANGE `id_sistema` `id_sistema` int(11) COMMENT 'Número que identifica o sistema.';
ALTER TABLE `mapeamento_unidade` CHANGE `id_unidade` `id_unidade` int(11) COMMENT 'Número que identifica a unidade.';
ALTER TABLE `mapeamento_unidade` CHANGE `id_origem` `id_origem` varchar(30) COMMENT 'Número que identifica a origem da unidade.';
ALTER TABLE `menu` CHANGE `id_menu` `id_menu` int(11) COMMENT 'Número que identifica o menu.';
ALTER TABLE `menu` CHANGE `id_sistema` `id_sistema` int(11) COMMENT 'Número que identifica o sistema.';
ALTER TABLE `menu` CHANGE `nome` `nome` varchar(50) COMMENT 'Nome do menu.';
ALTER TABLE `menu` CHANGE `descricao` `descricao` varchar(200) COMMENT 'Descrição do menu.';
ALTER TABLE `menu` CHANGE `sin_ativo` `sin_ativo` char(1) COMMENT 'Variável categórica que indica se o menu está ativo ou não. S: Sim N: Não';
ALTER TABLE `orgao` CHANGE `id_orgao` `id_orgao` int(11) COMMENT 'Número que identifica o órgão.';
ALTER TABLE `orgao` CHANGE `sigla` `sigla` varchar(30) COMMENT 'Sigla do órgão.';
ALTER TABLE `orgao` CHANGE `descricao` `descricao` varchar(100) COMMENT 'Descrição do órgão.';
ALTER TABLE `orgao` CHANGE `sin_ativo` `sin_ativo` char(1) COMMENT 'Variável categórica que indica se o órgão está ativo ou não. S: Sim N: Não';
ALTER TABLE `orgao` CHANGE `sin_autenticar` `sin_autenticar` char(1) COMMENT 'Variável categórica que indica se o órgão se autentica ou não. (Treinamento não é autenticado)';
ALTER TABLE `perfil` CHANGE `id_perfil` `id_perfil` int(11) COMMENT 'Número que identifica o perfil.';
ALTER TABLE `perfil` CHANGE `id_sistema` `id_sistema` int(11) COMMENT 'Número que identifica o sistema.';
ALTER TABLE `perfil` CHANGE `nome` `nome` varchar(50) COMMENT 'Nome do perfil.';
ALTER TABLE `perfil` CHANGE `descricao` `descricao` varchar(200) COMMENT 'Descrição do perfil.';
ALTER TABLE `perfil` CHANGE `sin_coordenado` `sin_coordenado` char(1) COMMENT 'Variável categórica que indica se o perfil está coordenado ou não. S: Sim N: Não';
ALTER TABLE `perfil` CHANGE `sin_avulso` `sin_avulso` char(1) COMMENT 'Variável categórica que indica se o perfil está avulso ou não. S: Sim N: Não';
ALTER TABLE `perfil` CHANGE `sin_ativo` `sin_ativo` char(1) COMMENT 'Variável categórica que indica se o perfil está ativo ou não. S: Sim N: Não';
ALTER TABLE `permissao` CHANGE `id_perfil` `id_perfil` int(11) COMMENT 'Número que identifica o perfil.';
ALTER TABLE `permissao` CHANGE `id_sistema` `id_sistema` int(11) COMMENT 'Número que identifica o sistema.';
ALTER TABLE `permissao` CHANGE `id_usuario` `id_usuario` int(11) COMMENT 'Número que identifica o usuário.';
ALTER TABLE `permissao` CHANGE `id_unidade` `id_unidade` int(11) COMMENT 'Número que identifica a unidade.';
ALTER TABLE `permissao` CHANGE `id_tipo_permissao` `id_tipo_permissao` int(11) COMMENT 'Número que identifica o tipo de permissão.';
ALTER TABLE `permissao` CHANGE `dta_inicio` `dta_inicio` datetime COMMENT 'Data e hora de início da permissão.';
ALTER TABLE `permissao` CHANGE `dta_fim` `dta_fim` datetime COMMENT 'Data e hora de conclusão da permissão.';
ALTER TABLE `permissao` CHANGE `sin_subunidades` `sin_subunidades` char(1) COMMENT 'Variável categórica que indica se a permissão para o usuário se estende às subunidades da unidade a qual foi concedida.';
ALTER TABLE `recurso` CHANGE `id_sistema` `id_sistema` int(11) COMMENT 'Número que identifica o sistema.';
ALTER TABLE `recurso` CHANGE `id_recurso` `id_recurso` int(11) COMMENT 'Número que identifica o recurso.';
ALTER TABLE `recurso` CHANGE `nome` `nome` varchar(50) COMMENT 'Nome do recurso (nome da função no código).';
ALTER TABLE `recurso` CHANGE `descricao` `descricao` varchar(200) COMMENT 'Descrição do recurso.';
ALTER TABLE `recurso` CHANGE `caminho` `caminho` varchar(255) COMMENT 'Caminho para o recurso.';
ALTER TABLE `recurso` CHANGE `sin_ativo` `sin_ativo` char(1) COMMENT 'Variável categórica que indica se o recurso está ativo ou não. S: Sim N: Não';
ALTER TABLE `recurso_vinculado` CHANGE `id_sistema` `id_sistema` int(11) COMMENT 'Número que identifica o sistema.';
ALTER TABLE `recurso_vinculado` CHANGE `id_recurso` `id_recurso` int(11) COMMENT 'Número que identifica o recurso.';
ALTER TABLE `recurso_vinculado` CHANGE `id_sistema_vinculado` `id_sistema_vinculado` int(11) COMMENT 'Número que identifica o sistema vinculado.';
ALTER TABLE `recurso_vinculado` CHANGE `id_recurso_vinculado` `id_recurso_vinculado` int(11) COMMENT 'Número que identifica o recurso vinculado.';
ALTER TABLE `recurso_vinculado` CHANGE `tipo_vinculo` `tipo_vinculo` int(11) COMMENT 'Número que identifica o tipo de vínculo do recurso.';
ALTER TABLE `regra_auditoria` CHANGE `id_regra_auditoria` `id_regra_auditoria` int(11) COMMENT 'Número que identifica a regra de auditoria.';
ALTER TABLE `regra_auditoria` CHANGE `descricao` `descricao` varchar(250) COMMENT 'Descrição da regra de auditoria.';
ALTER TABLE `regra_auditoria` CHANGE `id_sistema` `id_sistema` int(11) COMMENT 'Número que identifica o sistema.';
ALTER TABLE `regra_auditoria` CHANGE `sin_ativo` `sin_ativo` char(1) COMMENT 'Variável categórica que identifica se a regra de auditoria está ativa ou não. S: Sim N: Não';
ALTER TABLE `rel_grupo_rede_unidade` CHANGE `id_grupo_rede` `id_grupo_rede` int(11) COMMENT 'Número que identifica o grupo de rede.';
ALTER TABLE `rel_grupo_rede_unidade` CHANGE `id_unidade` `id_unidade` int(11) COMMENT 'Número que identifica a unidade.';
ALTER TABLE `rel_hierarquia_unidade` CHANGE `id_unidade` `id_unidade` int(11) COMMENT 'Número que identifica a unidade.';
ALTER TABLE `rel_hierarquia_unidade` CHANGE `id_hierarquia` `id_hierarquia` int(11) COMMENT 'Número que identifica a hierarquia.';
ALTER TABLE `rel_hierarquia_unidade` CHANGE `id_hierarquia_pai` `id_hierarquia_pai` int(11) COMMENT 'Número que identifica a hierarquia.';
ALTER TABLE `rel_hierarquia_unidade` CHANGE `id_unidade_pai` `id_unidade_pai` int(11) COMMENT 'Número que identifica a unidade superior na hierarquia.';
ALTER TABLE `rel_hierarquia_unidade` CHANGE `dta_inicio` `dta_inicio` datetime COMMENT 'Data de início da hierarquia.';
ALTER TABLE `rel_hierarquia_unidade` CHANGE `dta_fim` `dta_fim` datetime COMMENT 'Data de conclusão da hierarquia.';
ALTER TABLE `rel_hierarquia_unidade` CHANGE `sin_ativo` `sin_ativo` char(1) COMMENT 'Variável categórica que indica se a hierarquia está ativa ou não. S: Sim N: Não';
ALTER TABLE `rel_orgao_autenticacao` CHANGE `id_orgao` `id_orgao` int(11) COMMENT 'Número que identifica o órgão.';
ALTER TABLE `rel_orgao_autenticacao` CHANGE `id_servidor_autenticacao` `id_servidor_autenticacao` int(11) COMMENT 'Número que identifica o servidor de autenticação.';
ALTER TABLE `rel_orgao_autenticacao` CHANGE `sequencia` `sequencia` int(11) COMMENT 'Ordem de prioridade para autenticação.';
ALTER TABLE `rel_perfil_item_menu` CHANGE `id_perfil` `id_perfil` int(11) COMMENT 'Número de identificação do perfil.';
ALTER TABLE `rel_perfil_item_menu` CHANGE `id_sistema` `id_sistema` int(11) COMMENT 'Número de identificação do sistema.';
ALTER TABLE `rel_perfil_item_menu` CHANGE `id_menu` `id_menu` int(11) COMMENT 'Número de identificação do menu.';
ALTER TABLE `rel_perfil_item_menu` CHANGE `id_item_menu` `id_item_menu` int(11) COMMENT 'Número de identificação do item do menu.';
ALTER TABLE `rel_perfil_item_menu` CHANGE `id_recurso` `id_recurso` int(11) COMMENT 'Número de identificação do recurso.';
ALTER TABLE `rel_perfil_recurso` CHANGE `id_perfil` `id_perfil` int(11) COMMENT 'Número de identificação do perfil.';
ALTER TABLE `rel_perfil_recurso` CHANGE `id_sistema` `id_sistema` int(11) COMMENT 'Número de identificação do sistema.';
ALTER TABLE `rel_perfil_recurso` CHANGE `id_recurso` `id_recurso` int(11) COMMENT 'Número de identificação do recurso.';
ALTER TABLE `rel_regra_auditoria_recurso` CHANGE `id_recurso` `id_recurso` int(11) COMMENT 'Número de identificação do recurso.';
ALTER TABLE `rel_regra_auditoria_recurso` CHANGE `id_sistema` `id_sistema` int(11) COMMENT 'Número de identificação do sistema.';
ALTER TABLE `rel_regra_auditoria_recurso` CHANGE `id_regra_auditoria` `id_regra_auditoria` int(11) COMMENT 'Número de identificação da regra de auditoria.';
ALTER TABLE `seq_infra_auditoria` CHANGE `id` `id` bigint(20) COMMENT 'Número de identificação.';
ALTER TABLE `seq_infra_auditoria` CHANGE `campo` `campo` char(1) COMMENT 'Campo';
ALTER TABLE `seq_infra_log` CHANGE `id` `id` bigint(20) COMMENT 'Número de identificação do log.';
ALTER TABLE `seq_infra_log` CHANGE `campo` `campo` char(1) COMMENT 'Campo';
ALTER TABLE `servidor_autenticacao` CHANGE `id_servidor_autenticacao` `id_servidor_autenticacao` int(11) COMMENT 'Número que identifica o servidor de autenticação.';
ALTER TABLE `servidor_autenticacao` CHANGE `nome` `nome` varchar(50) COMMENT 'Nome do servidor de autenticação.';
ALTER TABLE `servidor_autenticacao` CHANGE `sta_tipo` `sta_tipo` varchar(10) COMMENT 'Tipo de servidor de autenticação.';
ALTER TABLE `servidor_autenticacao` CHANGE `endereco` `endereco` varchar(100) COMMENT 'Endereço do servidor de autenticação.';
ALTER TABLE `servidor_autenticacao` CHANGE `porta` `porta` int(11) COMMENT 'Número da porta do servidor de autenticação.';
ALTER TABLE `servidor_autenticacao` CHANGE `sufixo` `sufixo` varchar(50) COMMENT 'Sufixo do servidor de autenticação.';
ALTER TABLE `servidor_autenticacao` CHANGE `usuario_pesquisa` `usuario_pesquisa` varchar(100) COMMENT 'Nome de usuário.';
ALTER TABLE `servidor_autenticacao` CHANGE `senha_pesquisa` `senha_pesquisa` varchar(100) COMMENT 'Senha.';
ALTER TABLE `servidor_autenticacao` CHANGE `contexto_pesquisa` `contexto_pesquisa` varchar(100) COMMENT 'Identifica qual contexto foi feito o login do usuario.';
ALTER TABLE `servidor_autenticacao` CHANGE `atributo_filtro_pesquisa` `atributo_filtro_pesquisa` varchar(100) COMMENT 'Complemento ao filtro de pesquisa.';
ALTER TABLE `servidor_autenticacao` CHANGE `atributo_retorno_pesquisa` `atributo_retorno_pesquisa` varchar(100) COMMENT 'Complemento ao retorno de pesquisa.';
ALTER TABLE `servidor_autenticacao` CHANGE `versao` `versao` int(11) COMMENT 'Versão do servidor de autenticação.';
ALTER TABLE `sistema` CHANGE `id_sistema` `id_sistema` int(11) COMMENT 'Número que identifica o sistema.';
ALTER TABLE `sistema` CHANGE `id_orgao` `id_orgao` int(11) COMMENT 'Número que identifica o órgão.';
ALTER TABLE `sistema` CHANGE `id_hierarquia` `id_hierarquia` int(11) COMMENT 'Número que identifica a hierarquia.';
ALTER TABLE `sistema` CHANGE `sigla` `sigla` varchar(15) COMMENT 'Sigla do sistema.';
ALTER TABLE `sistema` CHANGE `descricao` `descricao` varchar(200) COMMENT 'Nome do sistema.';
ALTER TABLE `sistema` CHANGE `pagina_inicial` `pagina_inicial` varchar(255) COMMENT 'Endereço web do sistema.';
ALTER TABLE `sistema` CHANGE `sin_ativo` `sin_ativo` char(1) COMMENT 'Variável categórica que indica se o sistema está ativo ou não. S: Sim N: Não';
ALTER TABLE `sistema` CHANGE `web_service` `web_service` varchar(255) COMMENT 'Endereço web do webservice.';
ALTER TABLE `sistema` CHANGE `logo` `logo` longtext COMMENT 'Código de identificação do logo';
ALTER TABLE `tipo_permissao` CHANGE `id_tipo_permissao` `id_tipo_permissao` int(11) COMMENT 'Número que identifica o tipo de permissão.';
ALTER TABLE `tipo_permissao` CHANGE `descricao` `descricao` varchar(50) COMMENT 'Descrição do tipo de permissão.';
ALTER TABLE `unidade` CHANGE `id_unidade` `id_unidade` int(11) COMMENT 'Número que identifica a unidade.';
ALTER TABLE `unidade` CHANGE `id_orgao` `id_orgao` int(11) COMMENT 'Número que identifica o órgão.';
ALTER TABLE `unidade` CHANGE `sigla` `sigla` varchar(30) COMMENT 'Sigla da unidade.';
ALTER TABLE `unidade` CHANGE `descricao` `descricao` varchar(250) COMMENT 'Nome da unidade.';
ALTER TABLE `unidade` CHANGE `sin_ativo` `sin_ativo` char(1) COMMENT 'Variável categórica que identifica se a unidade está ativa ou não. S: Sim N: Não';
ALTER TABLE `unidade` CHANGE `sin_global` `sin_global` char(1) COMMENT 'Variável categórica que identifica se a unidade é global ou não. S: Sim N: Não';
ALTER TABLE `usuario` CHANGE `id_usuario` `id_usuario` int(11) COMMENT 'Número que identifica o usuário.';
ALTER TABLE `usuario` CHANGE `id_orgao` `id_orgao` int(11) COMMENT 'Número que identifica o órgão do usuário.';
ALTER TABLE `usuario` CHANGE `sigla` `sigla` varchar(100) COMMENT 'Sigla ou login de rede do usuário.';
ALTER TABLE `usuario` CHANGE `nome` `nome` varchar(100) COMMENT 'Nome do usuário.';
ALTER TABLE `usuario` CHANGE `sin_ativo` `sin_ativo` char(1) COMMENT 'Variável categórica que identifica se o usuário está ativo ou não. S: Sim N: Não';
ALTER TABLE `usuario` CHANGE `id_pessoa_rh` `id_pessoa_rh` bigint(20) COMMENT 'Número que identifica o cadastro do usuário em algum sistema de origem da instituição.';