/*
SCRIPT DE LIMPEZA DE PROCESSOS E DOCUMENTOS DA BASE DE DADOS DO SEI 5.0.0 (ORACLE)
  Antes de executar o script:
    1) Retirar o sistema do "AR" (derrubar todas sessões).
    2) Fazer uma cópia da base imediatamente antes de executar o script.
    3) Executar o script de limpeza. Se der erro, restaurar a base com a cópia feita no passo 2.

  Depois de executar o script com sucesso, sendo aconselhável conferir algumas tabelas abaixo e sequenciais de protocolo de processo na tabela "infra_sequencia":
    1) Apagar todos os arquivos e estrutura de pastas no Filesystem do sei_esquema.
    2) Excluir os Índices do Solr, conforme orientado no final do capítulo do Solr no Manual de Instalação do SEI:
      18 - Caso,  no  futuro,  seja  preciso  reindexar  todos  os  dados  é  aconselhável  limpar  antes  os  Índices usando os comandos abaixo:
        http://[servidor_solr]:8080/solr/sei-protocolos/update?stream.body=<delete><query>*:*</query></delete>&commit=true
				http://[servidor_solr]:8080/solr/sei-bases-conhecimento/update?stream.body=<delete><query>*:*</query></delete>&commit=true
				http://[servidor_solr]:8080/solr/sei-publicacoes/update?stream.body=<delete><query>*:*</query></delete>&commit=true
		4) Colocar o sistema de volta ao "AR".
*/


SELECT 'ALTER TABLE ' || owner || '.' || table_name || 
       ' DISABLE CONSTRAINT ' || constraint_name || ';'
FROM all_constraints
WHERE constraint_type = 'R'  -- Apenas chaves estrangeiras
AND owner = 'SEI';

 



--Fim - Desabilitando as FKs
/* Limpeza de tabelas afetas a Protocolo de Processos, de Documentos Gerados e Externos */


DELETE FROM ACAO_FEDERACAO;
DELETE FROM ACESSO;
DELETE FROM ACESSO_EXTERNO;
DELETE FROM ACESSO_FEDERACAO;
DELETE FROM ACOMPANHAMENTO;
DELETE FROM ANDAMENTO_INSTALACAO;
DELETE FROM ANDAMENTO_MARCADOR;
DELETE FROM ANDAMENTO_PLANO_TRABALHO;
DELETE FROM ANDAMENTO_SITUACAO;
DELETE FROM ANEXO;
DELETE FROM ANOTACAO;
DELETE FROM ARQUIVAMENTO;
DELETE FROM ASSINATURA;
DELETE FROM ATIVIDADE;
DELETE FROM ATRIBUTO_ANDAM_PLANO_TRAB;
DELETE FROM ATRIBUTO_ANDAMENTO;
DELETE FROM ATRIBUTO_INSTALACAO;
DELETE FROM AUDITORIA_PROTOCOLO;
DELETE FROM AVALIACAO_DOCUMENTAL;
DELETE FROM AVISO;
DELETE FROM BASE_CONHECIMENTO;
DELETE FROM BLOCO;
DELETE FROM CAMPO_PESQUISA;
DELETE FROM CATEGORIA;
DELETE FROM COMENTARIO;
DELETE FROM CONTROLE_PRAZO;
DELETE FROM DOCUMENTO;
DELETE FROM DOCUMENTO_CONTEUDO;
DELETE FROM DOCUMENTO_GERACAO;
DELETE FROM EDITAL_ELIMINACAO;
DELETE FROM EDITAL_ELIMINACAO_CONTEUDO;
DELETE FROM EDITAL_ELIMINACAO_ERRO;
DELETE FROM EMAIL_GRUPO_EMAIL;
DELETE FROM ESTATISTICAS;
DELETE FROM ETAPA_TRABALHO;
DELETE FROM FEED;
DELETE FROM GRUPO_ACOMPANHAMENTO;
DELETE FROM GRUPO_BLOCO;
DELETE FROM GRUPO_EMAIL;
DELETE FROM GRUPO_FEDERACAO;
DELETE FROM GRUPO_PROTOCOLO_MODELO;
DELETE FROM INFRA_CAPTCHA;
DELETE FROM INFRA_ERRO_PHP;
DELETE FROM INSTALACAO_FEDERACAO;
DELETE FROM ITEM_ETAPA;
DELETE FROM LEMBRETE;
DELETE FROM MARCADOR;
DELETE FROM MONITORAMENTO_SERVICO;
DELETE FROM NOTIFICACAO;
DELETE FROM NUMERACAO;
DELETE FROM OBSERVACAO;
DELETE FROM ORGAO_FEDERACAO;
DELETE FROM PARAMETRO_ACAO_FEDERACAO;
DELETE FROM PARTICIPANTE;
DELETE FROM PESQUISA;
DELETE FROM PLANO_TRABALHO;
DELETE FROM PROCEDIMENTO;
DELETE FROM PROTOCOLO;
DELETE FROM PROTOCOLO_FEDERACAO;
DELETE FROM PROTOCOLO_MODELO;
DELETE FROM PUBLICACAO;
DELETE FROM REABERTURA_PROGRAMADA;
DELETE FROM REL_ACESSO_EXT_PROTOCOLO;
DELETE FROM REL_ACESSO_EXT_SERIE;
DELETE FROM REL_AVISO_ORGAO;
DELETE FROM REL_BASE_CONHEC_TIPO_PROCED;
DELETE FROM REL_BLOCO_PROTOCOLO;
DELETE FROM REL_BLOCO_UNIDADE;
DELETE FROM REL_GRUPO_FED_ORGAO_FED;
DELETE FROM REL_ITEM_ETAPA_DOCUMENTO;
DELETE FROM REL_ITEM_ETAPA_SERIE;
DELETE FROM REL_ITEM_ETAPA_UNIDADE;
DELETE FROM REL_NOTIFICACAO_DOCUMENTO;
DELETE FROM REL_ORGAO_PESQUISA;
DELETE FROM REL_PROTOCOLO_ASSUNTO;
DELETE FROM REL_PROTOCOLO_ATRIBUTO;
DELETE FROM REL_PROTOCOLO_PROTOCOLO;
DELETE FROM REL_SERIE_PLANO_TRABALHO;
DELETE FROM REL_USUARIO_GRUPO_ACOMP;
DELETE FROM REL_USUARIO_GRUPO_BLOCO;
DELETE FROM REL_USUARIO_MARCADOR;
DELETE FROM REL_USUARIO_TIPO_PRIORIDADE;
DELETE FROM REL_USUARIO_TIPO_PROCED;
DELETE FROM REL_USUARIO_USUARIO_UNIDADE;
DELETE FROM REPLICACAO_FEDERACAO;
DELETE FROM RETORNO_PROGRAMADO;
DELETE FROM SECAO_DOCUMENTO;
DELETE FROM SERIE_ESCOLHA;
DELETE FROM SERIE_PUBLICACAO;
DELETE FROM SINALIZACAO_FEDERACAO;
DELETE FROM TEXTO_PADRAO_INTERNO;
DELETE FROM TIPO_PRIORIDADE;
DELETE FROM TIPO_PROCEDIMENTO_ESCOLHA;
DELETE FROM UNIDADE_FEDERACAO;
DELETE FROM UNIDADE_PUBLICACAO;
DELETE FROM USUARIO_FEDERACAO;
DELETE FROM VERSAO_SECAO_DOCUMENTO;
DELETE FROM LIXEIRA;
DELETE FROM ORGAO_HISTORICO;
DELETE FROM SOLICITACAO_OUVIDORIA;
DELETE FROM USUARIO_LOGIN;


--Reset Sequências (versão Oracle > 11)

ALTER SEQUENCE SEQ_ACESSO RESTART START WITH 1;
ALTER SEQUENCE SEQ_ACESSO_EXTERNO RESTART START WITH 1;
ALTER SEQUENCE SEQ_ACOMPANHAMENTO RESTART START WITH 1;
ALTER SEQUENCE SEQ_ANDAMENTO_MARCADOR RESTART START WITH 1;
ALTER SEQUENCE SEQ_ANDAMENTO_PLANO_TRABALHO RESTART START WITH 1;
ALTER SEQUENCE SEQ_ANDAMENTO_SITUACAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_ANEXO RESTART START WITH 1;
ALTER SEQUENCE SEQ_ANOTACAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_ASSINATURA RESTART START WITH 1;
ALTER SEQUENCE SEQ_ATIVIDADE RESTART START WITH 1;
ALTER SEQUENCE SEQ_ATRIBUTO_ANDAM_PLANO_TRAB RESTART START WITH 1;
ALTER SEQUENCE SEQ_ATRIBUTO_ANDAMENTO RESTART START WITH 1;
ALTER SEQUENCE SEQ_AUDITORIA_PROTOCOLO RESTART START WITH 1;
ALTER SEQUENCE SEQ_AVALIACAO_DOCUMENTAL RESTART START WITH 1;
ALTER SEQUENCE SEQ_AVISO RESTART START WITH 1;
ALTER SEQUENCE SEQ_BASE_CONHECIMENTO RESTART START WITH 1;
ALTER SEQUENCE SEQ_BLOCO RESTART START WITH 1;
ALTER SEQUENCE SEQ_CONTROLE_INTERNO RESTART START WITH 1;
ALTER SEQUENCE SEQ_EDITAL_ELIMINACAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_EDITAL_ELIMINACAO_CONTEUDO RESTART START WITH 1;
ALTER SEQUENCE SEQ_EDITAL_ELIMINACAO_ERRO RESTART START WITH 1;
ALTER SEQUENCE SEQ_EMAIL_GRUPO_EMAIL RESTART START WITH 1;
ALTER SEQUENCE SEQ_ESTATISTICAS RESTART START WITH 1;
ALTER SEQUENCE SEQ_ETAPA_TRABALHO RESTART START WITH 1;
ALTER SEQUENCE SEQ_FEED RESTART START WITH 1;
ALTER SEQUENCE SEQ_GRUPO_ACOMPANHAMENTO RESTART START WITH 1;
ALTER SEQUENCE SEQ_GRUPO_EMAIL RESTART START WITH 1;
ALTER SEQUENCE SEQ_GRUPO_PROTOCOLO_MODELO RESTART START WITH 1;
ALTER SEQUENCE SEQ_ITEM_ETAPA RESTART START WITH 1;
ALTER SEQUENCE SEQ_MARCADOR RESTART START WITH 1;
ALTER SEQUENCE SEQ_MONITORAMENTO_SERVICO RESTART START WITH 1;
ALTER SEQUENCE SEQ_NOTIFICACAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_NUMERACAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_OBSERVACAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_PARTICIPANTE RESTART START WITH 1;
ALTER SEQUENCE SEQ_PLANO_TRABALHO RESTART START WITH 1;
ALTER SEQUENCE SEQ_PROTOCOLO RESTART START WITH 1;
ALTER SEQUENCE SEQ_PROTOCOLO_MODELO RESTART START WITH 1;
ALTER SEQUENCE SEQ_PUBLICACAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_REABERTURA_PROGRAMADA RESTART START WITH 1;
ALTER SEQUENCE SEQ_REL_PROTOCOLO_PROTOCOLO RESTART START WITH 1;
ALTER SEQUENCE SEQ_RETORNO_PROGRAMADO RESTART START WITH 1;
ALTER SEQUENCE SEQ_SECAO_DOCUMENTO RESTART START WITH 1;
ALTER SEQUENCE SEQ_SERIE_PUBLICACAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_SITUACAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_TEXTO_PADRAO_INTERNO RESTART START WITH 1;
ALTER SEQUENCE SEQ_TIPO_FORMULARIO RESTART START WITH 1;
ALTER SEQUENCE SEQ_TIPO_PRIORIDADE RESTART START WITH 1;
ALTER SEQUENCE SEQ_TIPO_PROCED_RESTRICAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_UNIDADE_PUBLICACAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_UPLOAD RESTART START WITH 1;
ALTER SEQUENCE SEQ_VERSAO_SECAO_DOCUMENTO RESTART START WITH 1;

/* As seguintes tabelas devem ser avaliadas para exclusão dos dados inseridos pelos usuários

DELETE FROM ATRIBUTO;
DELETE FROM CARGO_FUNCAO;
DELETE FROM CONTROLE_INTERNO;
DELETE FROM CONTROLE_UNIDADE;
DELETE FROM DOMINIO;
DELETE FROM EMAIL_UTILIZADO;
DELETE FROM GRUPO_CONTATO;
DELETE FROM GRUPO_UNIDADE;
DELETE FROM LOCALIZADOR;
DELETE FROM LUGAR_LOCALIZADOR;
DELETE FROM MAPEAMENTO_ASSUNTO;
DELETE FROM NOVIDADE;
DELETE FROM OPERACAO_SERVICO;
DELETE FROM ORDENADOR_DESPESA;
DELETE FROM PUBLICACAO_LEGADO;
DELETE FROM REL_CONTROLE_INTERNO_ORGAO;
DELETE FROM REL_CONTROLE_INTERNO_SERIE;
DELETE FROM REL_CONTROLE_INTERNO_TIPO_PROC;
DELETE FROM REL_CONTROLE_INTERNO_UNIDADE;
DELETE FROM REL_GRUPO_CONTATO;
DELETE FROM REL_GRUPO_UNIDADE_UNIDADE;
DELETE FROM REL_SERIE_ASSUNTO;
DELETE FROM REL_SITUACAO_UNIDADE;
DELETE FROM SERIE_RESTRICAO;
DELETE FROM SERVICO;
DELETE FROM SITUACAO;
DELETE FROM TIPO_FORMULARIO;
DELETE FROM TIPO_LOCALIZADOR;
DELETE FROM TIPO_PROCED_RESTRICAO;
DELETE FROM TITULO;

//Reset Sequências (versão Oracle > 11)


ALTER SEQUENCE SEQ_ATRIBUTO RESTART START WITH 1;
ALTER SEQUENCE SEQ_CONTROLE_UNIDADE RESTART START WITH 1;
ALTER SEQUENCE SEQ_DOMINIO RESTART START WITH 1;
ALTER SEQUENCE SEQ_EMAIL_UTILIZADO RESTART START WITH 1;
ALTER SEQUENCE SEQ_GRUPO_CONTATO RESTART START WITH 1;
ALTER SEQUENCE SEQ_GRUPO_UNIDADE RESTART START WITH 1;
ALTER SEQUENCE SEQ_LOCALIZADOR RESTART START WITH 1;
ALTER SEQUENCE SEQ_LUGAR_LOCALIZADOR RESTART START WITH 1;
ALTER SEQUENCE SEQ_NOVIDADE RESTART START WITH 1;
ALTER SEQUENCE SEQ_OPERACAO_SERVICO RESTART START WITH 1;
ALTER SEQUENCE SEQ_ORDENADOR_DESPESA RESTART START WITH 1;
ALTER SEQUENCE SEQ_SERIE_RESTRICAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_SERVICO RESTART START WITH 1;
ALTER SEQUENCE SEQ_TIPO_LOCALIZADOR RESTART START WITH 1;

*/

/* Reconstrui as tabelas de log e auditoria e tabelas sequenciais correspondentes */
DELETE FROM INFRA_AUDITORIA;
DELETE FROM INFRA_LOG;
ALTER SEQUENCE SEQ_INFRA_AUDITORIA RESTART START WITH 1;
ALTER SEQUENCE SEQ_INFRA_LOG RESTART START WITH 1;

--Início - Habilitando as FKs

SELECT 'ALTER TABLE ' || owner || '.' || table_name || 
       ' ENABLE CONSTRAINT ' || constraint_name || ';'
FROM all_constraints
WHERE constraint_type = 'R'  
AND owner = 'SEI';

--Fim - Habilitando as FKs

/*
Sobre a última linha abaixo, a tabela de sequência anual de protocolo de processos pode ser qualquer um dos formatos abaixo (de acordo com a configuração da numeração de protocolo):
seq_[ano]_org_sip_[id sip]
seq_[ano]_org_sei_[cod sei]
seq_[ano]_uni_sip_[id sip]
seq_[ano]_uni_sei_[cod sei]
*/

delete from infra_sequencia where nome_tabela like 'seq_%_uni_sei_%';
delete from infra_sequencia where nome_tabela like 'seq_%_uni_sip_%';
delete from infra_sequencia where nome_tabela like 'seq_%_org_sei_%';
delete from infra_sequencia where nome_tabela like 'seq_%_org_sip_%';

update infra_sequencia set num_atual=0 where nome_tabela='infra_log';
update infra_sequencia set num_atual=0 where nome_tabela='infra_navegador';



/********************************************************************************************************************************************************/




